Repository ImisDevelopers/1_011_a_infektionsfall_uebermittellung, pull requests merged in 2020-05, with the labels that each got.

#283 Access REST-API permissions on client-side
  client/src/api/SwaggerApi.ts
  client/src/util/permissions.ts
  client/src/views/PatientDetails.vue
  server/src/main/java/de/coronavirus/imis/api/PermissionQueryController.java
  server/src/main/java/de/coronavirus/imis/config/SpringSecurityConfig.java
Labels: part-backend, part-client

#293 Fix Jackson LocalDate Serialization
  server/src/main/java/de/coronavirus/imis/config/PersistanceConfig.java
  server/src/main/resources/application.yml
Labels: bug, prio-high!!!

#310 Fix Selbstregistrierung
  server/src/main/java/de/coronavirus/imis/config/AuditorAwareImpl.java
  server/src/main/java/de/coronavirus/imis/config/SpringSecurityConfig.java
Labels: bug

#320 Improvements on clientside form utilities (code & docs)
  client/src/components/EditExposureContact.vue
  client/src/components/LocationFormGroup.vue
  client/src/components/PatientStammdaten.vue
  client/src/util/forms.ts
  client/src/util/typing.ts
Labels: documentation, part-client

#359 Fix/325
  client/src/components/LaboratoryInput.vue
  client/yarn.lock
Labels: bug

#319 Add exposure contact bulk insertion endpoint
  server/src/main/java/de/coronavirus/imis/api/ExposureContactController.java
  server/src/main/java/de/coronavirus/imis/repositories/ExposureContactRepository.java
  server/src/main/java/de/coronavirus/imis/services/util/BulkOperationService.java
Labels: part-backend

#405 Feature #346 fix search
  chart/templates/deployment.yaml
  chart/templates/persistent-volume.yaml
  client/src/views/PublicRegister.vue
  server/build.gradle
  server/src/main/java/de/coronavirus/imis/config/HibernateSearchConfig.java
  server/src/main/java/de/coronavirus/imis/domain/Patient.java
  server/src/main/java/de/coronavirus/imis/services/PatientQueryService.java
  server/src/main/java/de/coronavirus/imis/services/PatientService.java
  server/src/main/java/de/coronavirus/imis/services/RandomService.java
  server/src/main/java/de/coronavirus/imis/services/SearchService.java
  server/src/main/resources/application.yml
  server/src/test/java/de/coronavirus/imis/services/PatientServiceTest.java
  server/src/test/java/de/coronavirus/imis/services/RandomServiceTest.java
Labels: f-search
